### ISSUE TITLE
What could docker do to make it easier to do this correctly?

### ISSUE THREAD

**Issue by westurner** [Tecnativa/docker-socket-proxy#13]
What could docker do to make it easier to grant limited privileges to the docker socket(s) / API?

Are there existing issues in docker projects that should be prioritized to make this happen?

**Comment by pedrobaeza** [comment]
What this repository has to do with that?

**Comment by westurner** [comment]
You seem to have developed a solution that would be useful for upstream. As an expert who's spent time developing a solution, do you have any insight as to how docker could provide privilege-limited sockets without requiring a HAproxy instance to also keep upgraded?

**Comment by pedrobaeza** [comment]
Sorry, no

**Comment by westurner** [comment]
If docker were to provide a configuration option to create an additional socket(s) with a limited set(s) of API privileges, would this solution still be necessary?

**Comment by pedrobaeza** [comment]
I suppose not, but we should wait for that

**Comment by westurner** [comment]
Thanks for your time. Are you aware of any issues in any docker projects relevant to this concern?

**Comment by westurner** [comment]
I see these docs: https://docs.docker.com/v17.09/engine/security/https/

I'll spend some time looking through the open issues to see whether someone has requested a `(socket_filename, [perms,])` feature.

**Comment by Yajo** [comment]
After some recent reading and videos, I have become convinced that it's not just the socket: the whole security model under Docker is _broken by design_. [Read here why podman is way more secure](https://opensource.com/article/18/10/podman-more-secure-way-run-containers).

I think it makes more sense to invest time [in this new collection of container tools](https://youtu.be/40ynATurI7k) that is becoming available nowadays.

Apart from that, yes, limited privileges in sockets would be a good thing, but I don't think they'll apply that since Docker already ships with RBAC plugin support (although none is shipped by default in the CE edition), so those regards are supposed to be delegated to external plugins instead.

**Comment by westurner** [comment]
- https://github.com/google/gvisor
- https://cloud.google.com/blog/products/gcp/open-sourcing-gvisor-a-sandboxed-container-runtime
