### ISSUE TITLE
Provide dockerhub tags

### ISSUE THREAD

**Issue by seriousben** [Tecnativa/docker-socket-proxy#3]
Docket swarm does not like the use of the latest tag and might result in various versions running in the swarm.

Please provide tags for every "release".

**Comment by Yajo** [comment]
Docker swarm is fully compatible with `:latest` and whatever tags, it just converts that into a hash-pinned version (like normal docker, really). Did you know you can go to [the build details tab in the docker hub](https://hub.docker.com/r/tecnativa/docker-socket-proxy/builds/) and click on any of those builds, search for "digest" and get the hash-pinned version directly?

For instance, current latest is `tecnativa/docker-socket-proxy@sha256:dffeff5279100b6bbe3c91692eccfddfe8ed624ed8b276427f2870ad84379d01`.

I'm not planning maintaining several haproxy versions or things like that. This image's purpose is a very limited one and you should theoretically not care haproxy's version inside it. The only meaningful tag here would be `:latest` always, so I'm afraid I'm not going to add release versions because there's no notion of "release" here.
